apiVersion: v1
kind: Pod
metadata:
  name: testable1
  labels:
    app: webserver
spec:
  containers:
    - image: nginx:latest
      name: testable1
      ports:
        - containerPort: 3000
          name: http
          protocol: TCP
