apiVersion: v1
kind: Pod
metadata:
  name: testable4
spec:
  volumes:
    - name: "testable4-data"
      hostPath:
        path: "/home/marabesi/Public"
  containers:
    - image: nginx:latest
      name: testable4
      volumeMounts:
        - name: "testable4-data"
          mountPath: "/data"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
