apiVersion: v1
kind: Pod
metadata:
  name: giropops
spec:
  containers:
    - name: girus
      image: ubuntu
      args:
        - sleep
        - infinity
      volumeMounts:
      - name: whatever
        mountPath: /giropops
  volumes:
  - name: whatever
    emptyDir:
      sizeLimit: 256Mi
