apiVersion: v1
kind: Pod
metadata:
  name: testable2
spec:
  containers:
    - image: nginx:latest
      name: testable2
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 2
        periodSeconds: 10
        failureThreshold: 3
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
