apiVersion: v1
kind: Pod
metadata:
  name: testable3
spec:
  containers:
    - image: nginx:latest
      name: testable3
      resources:
        requests:
          cpu: "1000m"
          memory: "128Mi"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
