apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: my-replica
        image: "marabesi/host-info:latest"
